### ISSUE TITLE
What factors influence the ‘scannable cite’ ID?

### ISSUE THREAD

**Issue by ingo-m** [Juris-M/zotero-odf-scan-plugin#12]
Thanks for developing the zotero-odf-scan-plugin, this is a great tool (especially when working with collaborators who are still using proprietary software…).

I recently used the ‘RTF/ODF Scan’ plugin on a text document created a couple of months ago, but I was unable to convert the ‘scannable cite’ markers into active zotero references. I figured out that when I create new ‘scannable cite’ makers for the same references, the ID is different, e.g.:

{ | Saavedra, et al., 1969 | | |zu:0:H2DMZWXL}
{ | Saavedra, et al., 1969 | | |zu:0:2NHHQ4QY}

Much has changed since creating the original markers (new debian version, new zotero version) and I don’t know which factors play a role. How can I avoid this problem in the future? Which things have to stay constant for the IDs not to change?

Many thanks for your help.

**Comment by fbennett** [comment]
The OS and Zotero version changes will not affect the plugin. The most likely cause of the change in the ID is merging of duplicate entries in the database since your document was created. I have encountered this in my own writing, and I agree that it is an annoyance. Possibly we can account for this (behind the scenes, by looking up items by the URI derived from the key, which should account for the merge, rather than the raw key, which doesn't). For the present, the only way around it is to re-paste failed references with the current key.

**Comment by ingo-m** [comment]
@fbennett good to know and thanks for the quick reply!
