### ISSUE TITLE
Call from command line

### ISSUE THREAD

**Issue by jjstrydom** [Juris-M/zotero-odf-scan-plugin#5]
Would it be possible to call this from the command line or add support for it to be called from the command line?

**Comment by fbennett** [comment]
Not easily. Most of it is just JavaScript, but since you need access to the document owner's full set of Zotero libraries to recast the document, it's probably more comfortable left as a plugin. I reckon that it could be exposed to the command line in some way, as a server process that can be queried, but I don't know where you would start with that. Since Zotero itself is expected to switch platforms in the next year or so, it would probably make sense to wait, and work on something after the jump (to Electron, word is).
